# Generated by Django 2.2 on 2021-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('year', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('cc', models.CharField(max_length=100)),
                ('load_capacity', models.IntegerField()),
                ('pass_capacity', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('charge', models.FloatField()),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
