# Generated by Django 2.2 on 2021-01-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='registration',
            field=models.CharField(default='KG', max_length=250),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('third_name', models.CharField(max_length=250)),
                ('id_no', models.IntegerField()),
                ('model', models.SlugField(unique=True)),
                ('registration', models.CharField(default='KG', max_length=250)),
                ('period', models.CharField(max_length=100)),
                ('from1', models.DateField()),
                ('to', models.DateField()),
                ('car', models.ForeignKey(default='car', on_delete=django.db.models.deletion.CASCADE, to='Bookings.Cars')),
            ],
        ),
    ]
