# Generated by Django 2.2 on 2021-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210127_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rent',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
