# Generated by Django 2.2 on 2021-01-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_auto_20210127_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='from1',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='to',
            new_name='to_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='third_name',
        ),
    ]
