# Generated by Django 2.2 on 2021-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_auto_20210131_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
    ]
