# Generated by Django 2.2 on 2021-01-31 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_auto_20210131_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 31, 14, 46, 21, 4556)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 31, 14, 46, 21, 4556)),
        ),
    ]
