# Generated by Django 2.2 on 2021-01-31 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_auto_20210131_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 31, 14, 47, 32, 643516)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 31, 14, 47, 32, 643516)),
        ),
    ]
