# Generated by Django 2.2 on 2021-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_auto_20210131_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='car',
        ),
        migrations.AlterField(
            model_name='rent',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to_date',
            field=models.DateField(),
        ),
    ]
