# Generated by Django 2.2 on 2021-01-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_auto_20210131_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='id_no',
        ),
    ]
