# Generated by Django 2.2 on 2021-02-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_auto_20210201_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='model',
        ),
    ]
