# Generated by Django 2.2 on 2021-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0013_remove_rent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
